/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

interface VoxelDeskProps extends GroupProps {};

export function VoxelDesk(props: VoxelDeskProps) {
  const { nodes, materials } = useGLTF('/desk-voxel-no-floor.gltf')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.table.geometry}
          material={materials['Material.1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.keyboard.geometry}
          material={materials['Material.1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mouse.geometry}
          material={materials['Material.1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.monitor.geometry}
          material={materials['Material.1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.coffee.geometry}
          material={materials['Material.1']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/voxel-desk-art.gltf')
