import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { contentfulClient } from "@/contentful";
import { NavType } from "@/types";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ben.dev",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const entries = await contentfulClient.getEntries({
    content_type: "mainPages",
  });

  const navItems: NavType[] = entries.items
    .map((entry: any) => entry.fields)
    .sort((a: NavType, b: NavType) => a.sortOrder - b.sortOrder);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header navItems={navItems} />
        <main className="flex min-h-screen flex-col justify-between lg:px-24 md:w-[70vw] w-auto px-10 mx-auto">
          <main className="flex-1 flex-basis">{children}</main>
        </main>
        <Footer navItems={navItems} />
      </body>
    </html>
  );
}
